version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    environment:
      - DB_URL=postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres_proj_db:5432/${POSTGRES_DB}
    depends_on:
      - postgres_proj_db

  postgres_proj_db:
    container_name: postgres_proj_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}