version: "3.9"

volumes:
  pgdata: {}

services:
  social_media_app:
    container_name: social_media_app
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.dev
    environment:
      - DB_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@social_media_db:5432/${POSTGRES_DB}
    depends_on:
      - social_media_db

  social_media_db:
    container_name: social_media_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data