"""empty message

Revision ID: d115fd576d25
Revises: 5d39a38c124f
Create Date: 2023-11-21 18:56:35.602839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd115fd576d25'
down_revision = '5d39a38c124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('forget_password_token', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'user', ['forget_password_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'forget_password_token')
    # ### end Alembic commands ###
